version: '3.9'

services:
  frontend:
    container_name: nextjs-frontend-contianer
    image: ghcr.io/dumalbhaskar/assignment/frontend:v2.0
    ports:
      - 3000:3000
    environment:
      - NESTJS_URL=http://localhost:3001
    restart: always
    depends_on:
      - backend
  backend:
    container_name: nestjs-backend-container
    image: ghcr.io/dumalbhaskar/assignment/backend:v1.0
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypostgres
      POSTGRES_DB: todoapp
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
